port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
ipv6: false
allow-lan: true
mode: Rule
log-level: silent
external-controller: 0.0.0.0:9090
external-ui: ui
secret: ""
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  default-nameserver:
    - 114.114.114.114
  #enhanced-mode: redir-host
  enhanced-mode: fake-ip #如果要玩netflix，需要使用fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - tls://8.8.8.8:853
  fallback:
    - tls://8.8.8.8:853
tun:
  enable: true
  stack: system # or gvisor
  dns-hijack:
    - tcp://8.8.8.8:53

# 代理服务器配置
proxies:
  - name: "jms-s1"
    type: ss
    server: 
    port: 12345
    cipher: aes-256-gcm
    password: ""
# 配置 Group
proxy-groups:
  # 自动切换
  - name: "auto"
    type: url-test
    url: "http://www.gstatic.com/generate_204"
    proxies:
      - "jms-s1"
    interval: 300
  # 按需选择 - 可以在UI上选择
  - name: "Proxy"
    type: select
    proxies:
      - "jms-s1"
rules:
  # LAN
  - DOMAIN-SUFFIX,local,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  # 最终规则（除了中国区的IP之外的，全部翻墙）
  - GEOIP,CN,DIRECT
  - MATCH,auto
